# Generated by Django 3.0.3 on 2020-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200302_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='individu',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
