# Generated by Django 3.0.3 on 2020-03-03 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_candidat_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_cree',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='date_dip',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_dip',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='date_enregristrement',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
