# Generated by Django 3.0.3 on 2020-03-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200304_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='cin',
        ),
    ]
