# Generated by Django 3.0.3 on 2020-03-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200310_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='cin',
        ),
    ]
