# Generated by Django 3.0.3 on 2020-03-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_candidat_cin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='cin',
            new_name='cine',
        ),
    ]
