# Generated by Django 4.0.4 on 2022-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0131_auto_20200507_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='my_status',
            field=models.CharField(choices=[('professeur', 'professeur'), ('candidat', 'candidat'), ('doctorant', 'doctorant')], default='candidat', max_length=15),
        ),
    ]
