# Generated by Django 3.0.3 on 2020-02-28 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidat',
            fields=[
                ('num_insc', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('fonction', models.CharField(max_length=60)),
                ('entreprise', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='compte',
            fields=[
                ('ref_compte', models.AutoField(primary_key=True, serialize=False)),
                ('date_cree', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='diplome',
            fields=[
                ('code_dip', models.CharField(choices=[('mst001', 'mst001'), ('mst002', 'mst002'), ('ing001', 'ing001')], max_length=20, primary_key=True, serialize=False)),
                ('type_dip', models.CharField(default='', max_length=100)),
                ('date_dip', models.DateTimeField()),
                ('libelle_dip', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctorant',
            fields=[
                ('id_doctorant', models.AutoField(primary_key=True, serialize=False)),
                ('date_dip', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='enregistrement',
            fields=[
                ('id_enregistrement', models.AutoField(primary_key=True, serialize=False)),
                ('rapport', models.CharField(default='', max_length=100)),
                ('articles', models.CharField(default='', max_length=100)),
                ('date_enregristrement', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='equipe_recherche',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_equipe', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='individu',
            fields=[
                ('cin', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenoms', models.CharField(default='', max_length=42)),
                ('photo', models.ImageField(default='', upload_to='')),
                ('mail', models.EmailField(default='exemple@gmail.com', max_length=30)),
                ('tel', models.CharField(default='', max_length=15)),
                ('addr', models.CharField(default='', max_length=60)),
                ('ville_residence', models.CharField(default='', max_length=250)),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=15)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=15)),
                ('etat_civil', models.CharField(choices=[('Celibataire', 'Celibataire'), ('Marié', 'Marié'), ('Veuf/Veuve', 'Veuf/Veuve')], max_length=15)),
                ('date_nais', models.DateField(default=datetime.datetime.now)),
                ('est_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='these',
            fields=[
                ('id_these', models.AutoField(primary_key=True, serialize=False)),
                ('titre_these', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professeur',
            fields=[
                ('code_prof', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('id_doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.doctorant')),
                ('ref_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.compte')),
            ],
        ),
        migrations.CreateModel(
            name='posseder_dip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_dip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.diplome')),
                ('id_doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='labo',
            fields=[
                ('id_labo', models.CharField(choices=[('001', '001'), ('002', '002')], max_length=100, primary_key=True, serialize=False)),
                ('libelle_labo', models.CharField(default='', max_length=100)),
                ('id_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.equipe_recherche')),
            ],
        ),
        migrations.CreateModel(
            name='jury',
            fields=[
                ('code_jury', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_jury', models.CharField(default='', max_length=100)),
                ('code_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='equipe_recherche',
            name='code_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.professeur'),
        ),
        migrations.AddField(
            model_name='equipe_recherche',
            name='id_doctorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.doctorant'),
        ),
        migrations.AddField(
            model_name='doctorant',
            name='id_these',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.these'),
        ),
        migrations.AddField(
            model_name='doctorant',
            name='num_insc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.candidat'),
        ),
        migrations.AddField(
            model_name='doctorant',
            name='ref_compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.compte'),
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('code_jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.jury')),
                ('ref_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.compte')),
            ],
        ),
    ]
