# Generated by Django 3.0.3 on 2020-02-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200229_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='code_dip',
        ),
    ]
