# Generated by Django 3.0.3 on 2020-03-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_individu_code_dip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admini',
        ),
    ]
