# Generated by Django 3.0.3 on 2020-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200303_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=6)),
                ('lname', models.CharField(default='', max_length=6)),
                ('mail', models.EmailField(max_length=30)),
            ],
        ),
    ]
