# Generated by Django 3.0.3 on 2020-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_candidat_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='date',
        ),
        migrations.AlterField(
            model_name='diplome',
            name='type_dip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='individu',
            name='etat_civil',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='individu',
            name='genre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='individu',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='individu',
            name='prenoms',
            field=models.CharField(default='', max_length=50),
        ),
    ]
