# Generated by Django 3.0.3 on 2020-03-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200304_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
