# Generated by Django 3.0.3 on 2020-03-12 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20200311_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='cine',
        ),
        migrations.AddField(
            model_name='candidat',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplome',
            field=models.ManyToManyField(to='pages.diplome'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='individu',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.individu'),
        ),
        migrations.AddField(
            model_name='individu',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diplome',
            name='date_dip',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='individu',
            name='cin',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
