# Generated by Django 3.0.3 on 2020-03-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20200312_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalite',
            name='cin',
        ),
    ]
