# Generated by Django 3.0.3 on 2020-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20200312_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date',
            field=models.DateField(),
        ),
    ]
